//
// CharCategoryTest.cs
//
// Author:
//	Atsushi Enomoto <atsushi@ximian.com>
//
// (C)2004 Novell Inc.
//
// Brute force tests for Char.IsXXX() static methods.
// The result string is generated by the short program, which ran under MS.NET.
// (See the bottom of this file.)
//

using NUnit.Framework;
using System;
using System.IO;
using System.Reflection;

namespace MonoTests.System
{
    [TestFixture]
    public class CharCategoryTest : Assertion
    {
        delegate bool ComparisonMethod(char c);

        private static void Dump(ComparisonMethod cm)
        {
            string s = "";
            int k = 0;
            for (int i = 0; i <= Char.MaxValue; i++)
            {
                if (cm((char)i))
                {
                    s += i.ToString("x");
                    ++k;
                }
            }
            Console.WriteLine(s);
        }

        [Test]
        public void IsControl()
        {
            Dump(Char.IsControl);
        }

        [Test]
        public void IsDigit()
        {
            Dump(Char.IsDigit);
        }

        [Test]
        [Ignore("The dump file is huge, so avoided this test way.")]
        public void IsLetter()
        {
            Dump(Char.IsLetter);
        }

        [Test]
        [Ignore("The dump file is huge, so avoided this test way.")]
        public void IsLetterOrDigit()
        {
            Dump(Char.IsLetterOrDigit);
        }

        [Test]
        public void IsLower()
        {
            Dump(Char.IsLower);
        }

        [Test]
        public void IsNumber()
        {
            Dump(Char.IsNumber);
        }

        [Test]
        public void IsPunctuation()
        {
            Dump(Char.IsPunctuation);
        }

        [Test]
        public void IsSeparator()
        {
            Dump(Char.IsSeparator);
        }

        [Test]
        public void IsSurrogate()
        {
            Dump(Char.IsSurrogate);
        }

        [Test]
        public void IsSymbol()
        {
            Dump(Char.IsSymbol);
        }

        [Test]
        public void IsUpper()
        {
            Dump(Char.IsUpper);
        }

        [Test]
        public void IsWhiteSpace()
        {
            Dump(Char.IsWhiteSpace);
        }
    }
}
