using System;

#region Declaration

public class A99<T99>
{
    public class A98<T98> : A99<T98>
    {
        public class A97<T97> : A98<T97>
        {
            public class A96<T96> : A97<T96>
            {
                public class A95<T95> : A96<T95>
                {
                    public class A94<T94> : A95<T94>
                    {
                        public class A93<T93> : A94<T93>
                        {
                            public class A92<T92> : A93<T92>
                            {
                                public class A91<T91> : A92<T91>
                                {
                                    public class A90<T90> : A91<T90>
                                    {
                                        public class A89<T89> : A90<T89>
                                        {
                                            public class A88<T88> : A89<T88>
                                            {
                                                public class A87<T87> : A88<T87>
                                                {
                                                    public class A86<T86> : A87<T86>
                                                    {
                                                        public class A85<T85> : A86<T85>
                                                        {
                                                            public class A84<T84> : A85<T84>
                                                            {
                                                                public class A83<T83> : A84<T83>
                                                                {
                                                                    public class A82<T82> : A83<T82>
                                                                    {
                                                                        public class A81<T81> : A82<T81>
                                                                        {
                                                                            public class A80<T80> : A81<T80>
                                                                            {
                                                                                public class A79<T79> : A80<T79>
                                                                                {
                                                                                    public class A78<T78> : A79<T78>
                                                                                    {
                                                                                        public class A77<T77> : A78<T77>
                                                                                        {
                                                                                            public class A76<T76> : A77<T76>
                                                                                            {
                                                                                                public class A75<T75> : A76<T75>
                                                                                                {
                                                                                                    public class A74<T74> : A75<T74>
                                                                                                    {
                                                                                                        public class A73<T73> : A74<T73>
                                                                                                        {
                                                                                                            public class A72<T72> : A73<T72>
                                                                                                            {
                                                                                                                public class A71<T71> : A72<T71>
                                                                                                                {
                                                                                                                    public class A70<T70> : A71<T70>
                                                                                                                    {
                                                                                                                        public class A69<T69> : A70<T69>
                                                                                                                        {
                                                                                                                            public class A68<T68> : A69<T68>
                                                                                                                            {
                                                                                                                                public class A67<T67> : A68<T67>
                                                                                                                                {
                                                                                                                                    public class A66<T66> : A67<T66>
                                                                                                                                    {
                                                                                                                                        public class A65<T65> : A66<T65>
                                                                                                                                        {
                                                                                                                                            public class A64<T64> : A65<T64>
                                                                                                                                            {
                                                                                                                                                public class A63<T63> : A64<T63>
                                                                                                                                                {
                                                                                                                                                    public class A62<T62> : A63<T62>
                                                                                                                                                    {
                                                                                                                                                        public class A61<T61> : A62<T61>
                                                                                                                                                        {
                                                                                                                                                            public class A60<T60> : A61<T60>
                                                                                                                                                            {
                                                                                                                                                                public class A59<T59> : A60<T59>
                                                                                                                                                                {
                                                                                                                                                                    public class A58<T58> : A59<T58>
                                                                                                                                                                    {
                                                                                                                                                                        public class A57<T57> : A58<T57>
                                                                                                                                                                        {
                                                                                                                                                                            public class A56<T56> : A57<T56>
                                                                                                                                                                            {
                                                                                                                                                                                public class A55<T55> : A56<T55>
                                                                                                                                                                                {
                                                                                                                                                                                    public class A54<T54> : A55<T54>
                                                                                                                                                                                    {
                                                                                                                                                                                        public class A53<T53> : A54<T53>
                                                                                                                                                                                        {
                                                                                                                                                                                            public class A52<T52> : A53<T52>
                                                                                                                                                                                            {
                                                                                                                                                                                                public class A51<T51> : A52<T51>
                                                                                                                                                                                                {
                                                                                                                                                                                                    public class A50<T50> : A51<T50>
                                                                                                                                                                                                    {
                                                                                                                                                                                                        public class A49<T49> : A50<T49>
                                                                                                                                                                                                        {
                                                                                                                                                                                                            public class A48<T48> : A49<T48>
                                                                                                                                                                                                            {
                                                                                                                                                                                                                public class A47<T47> : A48<T47>
                                                                                                                                                                                                                {
                                                                                                                                                                                                                    public class A46<T46> : A47<T46>
                                                                                                                                                                                                                    {
                                                                                                                                                                                                                        public class A45<T45> : A46<T45>
                                                                                                                                                                                                                        {
                                                                                                                                                                                                                            public class A44<T44> : A45<T44>
                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                public class A43<T43> : A44<T43>
                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                    public class A42<T42> : A43<T42>
                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                        public class A41<T41> : A42<T41>
                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                            public class A40<T40> : A41<T40>
                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                public class A39<T39> : A40<T39>
                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                    public class A38<T38> : A39<T38>
                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                        public class A37<T37> : A38<T37>
                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                            public class A36<T36> : A37<T36>
                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                public class A35<T35> : A36<T35>
                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                    public class A34<T34> : A35<T34>
                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                        public class A33<T33> : A34<T33>
                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                            public class A32<T32> : A33<T32>
                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                public class A31<T31> : A32<T31>
                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                    public class A30<T30> : A31<T30>
                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                        public class A29<T29> : A30<T29>
                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                            public class A28<T28> : A29<T28>
                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                public class A27<T27> : A28<T27>
                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                    public class A26<T26> : A27<T26>
                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                        public class A25<T25> : A26<T25>
                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                            public class A24<T24> : A25<T24>
                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                public class A23<T23> : A24<T23>
                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                    public class A22<T22> : A23<T22>
                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                        public class A21<T21> : A22<T21>
                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                            public class A20<T20> : A21<T20>
                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                public class A19<T19> : A20<T19>
                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                    public class A18<T18> : A19<T18>
                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                        public class A17<T17> : A18<T17>
                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                            public class A16<T16> : A17<T16>
                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                public class A15<T15> : A16<T15>
                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                    public class A14<T14> : A15<T14>
                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                        public class A13<T13> : A14<T13>
                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                            public class A12<T12> : A13<T12>
                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                public class A11<T11> : A12<T11>
                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                    public class A10<T10> : A11<T10>
                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                        public class A9<T9> : A10<T9>
                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                            public class A8<T8> : A9<T8>
                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                public class A7<T7> : A8<T7>
                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                    public class A6<T6> : A7<T6>
                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                        public class A5<T5> : A6<T5>
                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                            public class A4<T4> : A5<T4>
                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                public class A3<T3> : A4<T3>
                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                    public class A2<T2> : A3<T2>
                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                        public class A1<T1> : A2<T1>
                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                            public T1 Foo()
                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                return default(T1);
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                }
                                                                                                                                                                                                            }
                                                                                                                                                                                                        }
                                                                                                                                                                                                    }
                                                                                                                                                                                                }
                                                                                                                                                                                            }
                                                                                                                                                                                        }
                                                                                                                                                                                    }
                                                                                                                                                                                }
                                                                                                                                                                            }
                                                                                                                                                                        }
                                                                                                                                                                    }
                                                                                                                                                                }
                                                                                                                                                            }
                                                                                                                                                        }
                                                                                                                                                    }
                                                                                                                                                }
                                                                                                                                            }
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

#endregion

class Test
{
    static void Test1()
    {
        Console.WriteLine("----Test1");
        try
        {
            A99<float>.A98<int>.A97<short>.A96<short>.A95<char>.A94<double>.A93<double>.A92<int>.A91<double>.A90<double>.A89<char>.A88<double>.A87<double>.A86<short>.A85<short>.A84<char>.A83<float>.A82<float>.A81<double>.A80<float>.A79<float>.A78<int>.A77<char>.A76<int>.A75<float>.A74<char>.A73<float>.A72<double>.A71<int>.A70<float>.A69<short>.A68<char>.A67<double>.A66<short>.A65<double>.A64<char>.A63<double>.A62<int>.A61<float>.A60<float>.A59<double>.A58<int>.A57<double>.A56<int>.A55<int>.A54<char>.A53<int>.A52<short>.A51<double>.A50<char>.A49<char>.A48<double>.A47<int>.A46<int>.A45<short>.A44<double>.A43<double>.A42<short>.A41<int>.A40<int>.A39<char>.A38<int>.A37<char>.A36<short>.A35<float>.A34<char>.A33<char>.A32<short>.A31<double>.A30<char>.A29<short>.A28<double>.A27<char>.A26<char>.A25<double>.A24<double>.A23<char>.A22<short>.A21<char>.A20<short>.A19<short>.A18<char>.A17<char>.A16<double>.A15<short>.A14<double>.A13<char>.A12<int>.A11<char>.A10<char>.A9<short>.A8<float>.A7<char>.A6<float>.A5<short>.A4<int>.A3<double>.A2<float>.A1<short> a = new A99<float>.A98<int>.A97<short>.A96<short>.A95<char>.A94<double>.A93<double>.A92<int>.A91<double>.A90<double>.A89<char>.A88<double>.A87<double>.A86<short>.A85<short>.A84<char>.A83<float>.A82<float>.A81<double>.A80<float>.A79<float>.A78<int>.A77<char>.A76<int>.A75<float>.A74<char>.A73<float>.A72<double>.A71<int>.A70<float>.A69<short>.A68<char>.A67<double>.A66<short>.A65<double>.A64<char>.A63<double>.A62<int>.A61<float>.A60<float>.A59<double>.A58<int>.A57<double>.A56<int>.A55<int>.A54<char>.A53<int>.A52<short>.A51<double>.A50<char>.A49<char>.A48<double>.A47<int>.A46<int>.A45<short>.A44<double>.A43<double>.A42<short>.A41<int>.A40<int>.A39<char>.A38<int>.A37<char>.A36<short>.A35<float>.A34<char>.A33<char>.A32<short>.A31<double>.A30<char>.A29<short>.A28<double>.A27<char>.A26<char>.A25<double>.A24<double>.A23<char>.A22<short>.A21<char>.A20<short>.A19<short>.A18<char>.A17<char>.A16<double>.A15<short>.A14<double>.A13<char>.A12<int>.A11<char>.A10<char>.A9<short>.A8<float>.A7<char>.A6<float>.A5<short>.A4<int>.A3<double>.A2<float>.A1<short>();
            a.Foo();
            Console.WriteLine("ok");
        }
        catch (Exception e)
        {
            Console.WriteLine(e.GetType());
        }
    }

    static void Main()
    {
        Test1();
        Console.WriteLine("<%END%>");
    }
}
