rv /T:System.SByte /out:Int8.cs Template.cs
rv /T:System.Byte /out:UInt8.cs Template.cs
rv /T:System.Int16 /out:Int16.cs Template.cs 
rv /T:System.UInt16 /out:UInt16.cs Template.cs 
rv /T:System.Int32 /out:Int32.cs Template.cs
rv /T:System.UInt32 /out:UInt32.cs Template.cs
rv /T:System.Int64 /out:Int64.cs Template.cs
rv /T:System.UInt64 /out:UInt64.cs Template.cs
rv /T:System.Double /out:Double.cs Template.cs
rv /T:System.Single /out:Single.cs Template.cs
rv /T:System.Char /out:Char.cs Template.cs
rv /T:EInt8 /out:EInt8.cs Template.cs
rv /T:EUInt8 /out:EUInt8.cs Template.cs
rv /T:EInt16 /out:EInt16.cs Template.cs
rv /T:EUInt16 /out:EUInt16.cs Template.cs
rv /T:EInt32 /out:EInt32.cs Template.cs
rv /T:EUInt32 /out:EUInt32.cs Template.cs
rv /T:EInt64 /out:EInt64.cs Template.cs
rv /T:EUInt64 /out:EUInt64.cs Template.cs