using DataDynamics.PageFX.Common.CodeModel;
using DataDynamics.PageFX.Common.Collections;
using DataDynamics.PageFX.Common.Syntax;

namespace DataDynamics.PageFX.Common.TypeSystem
{
	/// <summary>
    /// Represents type.
    /// </summary>
    public interface IType : ITypeMember, ITypeContainer
    {
        /// <summary>
        /// Gets or sets namespace where type is defined.
        /// </summary>
        string Namespace { get; set; }

        /// <summary>
        /// Gets kind of the type.
        /// </summary>
        TypeKind TypeKind { get; }
        
        /// <summary>
        /// Gets or sets flag specifing that this type is abstract.
        /// </summary>
        bool IsAbstract { get; set; }

        /// <summary>
        /// Gets or sets flag specifing that this type is sealed.
        /// </summary>
        bool IsSealed { get; set; }

        bool IsBeforeFieldInit { get; set; }

        /// <summary>
        /// Gets or sets the flag indicating wheher the type is generated by compiler.
        /// </summary>
        bool IsCompilerGenerated { get; set; }

        /// <summary>
        /// Determines whether this type is interface.
        /// </summary>
        bool IsInterface { get; }

        /// <summary>
        /// Determines whether this type is class.
        /// </summary>
        bool IsClass { get; }

        /// <summary>
        /// Determines whether this type is array.
        /// </summary>
        bool IsArray { get; }

        /// <summary>
        /// Determines whether this type is enum type.
        /// </summary>
        bool IsEnum { get; }

        bool HasIEnumerableInstance { get; set; }

        IMethod DeclaringMethod { get; set; }

        IType BaseType { get; set; }

        ITypeCollection Interfaces { get; }

        IType ValueType { get; }

        /// <summary>
        /// Gets the fields declared in this type.
        /// </summary>
        IFieldCollection Fields { get; }

        /// <summary>
        /// Gets the methods declared in this type.
        /// </summary>
        IMethodCollection Methods { get; }

        /// <summary>
        /// Gets the properties declared in this type.
        /// </summary>
        IPropertyCollection Properties { get; }

        /// <summary>
        /// Gets the events declared in this type.
        /// </summary>
        IEventCollection Events { get; }

        /// <summary>
        /// Gets the members declared in this type.
        /// </summary>
        ITypeMemberCollection Members { get; }

        ClassLayout Layout { get; set; }

        /// <summary>
        /// Gets or sets members defined with syntax of some language
        /// </summary>
        string CustomMembers { get; set; }

        /// <summary>
        /// Gets or sets type source code.
        /// </summary>
        string SourceCode { get; set; }

		/// <summary>
        /// Gets unique key of this type. Used for <see cref="TypeFactory"/>.
        /// </summary>
        string Key { get;  }

        /// <summary>
        /// Gets name of the type used in signatures.
        /// </summary>
        string SigName { get; }

        /// <summary>
        /// Name with names of enclosing types.
        /// </summary>
        string NestedName { get; }
    }

	public interface ITypeCollection : IReadOnlyList<IType>, ICodeNode
    {
		IType FindType(string fullname);

		void Add(IType type);

        bool Contains(IType type);
    }

	public enum TypeKind : byte
	{
		[CSharp("class")]
		[VB("Class")]
		[ActionScript("class")]
		Class,

		[CSharp("interface")]
		[VB("Interface")]
		[ActionScript("interface")]
		Interface,

		[CSharp("struct")]
		[VB("Struct")]
		[ActionScript("class")]
		Struct,

		[CSharp("enum")]
		[VB("Enumeration")]
		[ActionScript("class")]
		Enum,

		[CSharp("delegate")]
		Delegate,

		GenericParameter,

		Array,
		Reference,
		Pointer,

		[CSharp("struct")]
		[VB("Struct")]
		Primitive,
	}

	public enum TypeNameKind
    {
        FullName,
        Name,
        DisplayName,
        NestedName,
        SigName,
        Key,
        CSharpKeyword
    }
}